config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "prompts#index"

  resources :prompts, only: %i[ index ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/prompt.rb
class Prompt < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  validates :body, presence: true

  index_name([Rails.env,base_class.to_s.pluralize.underscore].join('_'))
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  def index
    @prompts = Prompt.search(params[:q].presence || '*').paginate(page: params[:page], per_page: 20).results
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Assignment1
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    .container
      = yield

app/views/prompts/index.html.haml
.d-block.border.border-primary.rounded.p-2.mt-2
  = form_tag prompts_path, method: 'get', class: 'form-inline my-2 my-lg-0' do
    = text_field_tag :q, params[:q], class: 'form-control mr-sm-2', type: 'search', aria: { label: 'Search' }
    = submit_tag t('helpers.buttons.search'), class: 'btn btn-outline-success my-2 my-sm-0 mx-auto d-block', type: 'submit'
%dl.mt-2
  - @prompts.each do |prompt|
    %dd= prompt.body
    %hr

= will_paginate @prompts, params: { q: params[:q] }